openapi: 3.0.1
info:
  title: Todos server
  description: todos server specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /api/todos:
    get:
      summary: Returns all saved todos.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEntities'
  /fetchedTodo/{id}:
    get:
      summary: Returns todo by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEntity'
  /fetchList:
    get:
      summary: Fetch list of 4 todos from remote server
      responses:
        '200':
          description: Fetched successfully
          content:
            application/json:
              schema:
                type: string
  /fullTemperatureInfo:
    get:
      summary: Returns full temperature info
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                
components:
  schemas:
    Todo:
      properties:
        userId:
          type: integer
        id:
          type: integer
        title:
          type: string
        isComprleted:
          type: boolean

    ResponseEntities:
      properties:
        body:
          type: array
          items:
            $ref: '#/components/schemas/Todo'
    ResponseEntity:
      properties:
        body:
          type: array
          items:
            $ref: '#/components/schemas/Todo'

